### ISSUE TITLE
Wraith cannot detect BO1 if a mod is active (game_mod)

### ISSUE THREAD

**Issue by Roachisserie** [dtzxporter/WraithXArchon#1]
Title says all, really. I've tried it with multiple mods.
The process name stays the same (BlackOps.exe) so i'm not sure why the issue exists?

**Comment by dtzxporter** [comment]
Please note that wraith is no longer in development. That said, run Wraith as admin.

**Comment by Roachisserie** [comment]
> Please note that wraith is no longer in development. That said, run Wraith as admin.

just gives a "the current game is supported but this update is not, please wait for a patch"
